sudo: required
services: 
  - docker 

before_install: 
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: Docker-react
  env: "Dockerreact-env-1"
  bucket_name: elasticbeanstalk-us-east-1-224221470270
  bucket_path: Docker_react
  on: 
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY